### PR TITLE
various enhancements and reworks

### PR DESCRIPTION
**Pull request by jacob-keller**
EDIT: This patch series has grown enormously since it launched. I've updated the description as such.

This rather long patch series implements proposed fixes for Issue #46, specifically the issue created by trade being limited to catpower. Essentially we rarely trade, leaving gold capped at max a long time.

This patch series fixes this along with some other refactors I worked on the way. I tried to break things up smoothly where possible.

Some contentious bits:

a) this series removes luxury type distinction for resources

I think this is really limiting, as it forces us to hunt to craft parchment, *even* if we produce enough via mints. Instead, just treat parchment like a limited craft by default. The user has enough control, and can even force stocks in place via javascript console. In the long term we want this to go away anyways, but I think we're good enough now, given the changes. Furs don't serve any other purpose besides happiness anyways.

If the user wishes, they can disable parchment and micromanage it, (though they lose a lot of wasted time when science/culture are full, preventing creation of manuscripts and compendium)

b) split out stocks to their own area

since not all resources can be crafted, it seemed silly to keep stocks inside the crafting section. Instead, I made their own section and added a base 1k stock for fur. This seems reasonable as it will prevent parchment trading if we go below 1000 furs. I think when you're this low, you can probably get by with manual intervention.

In addition, this ensures that we never make parchments reduce us to near zero furs. We do our best to maintain the happiness source.

c) trading will try to ensure some reasonable split between all available races

It tries to split up the races so that each race can only trade maximum of 1/n * (max times we could trade catpower/gold). This helps ensure that we don't starve races by being out of order. It might be possible to come up with a better system, but this is somewhat intuitive and prevents race starvation.

The other changes are  basically suggestions from Mewnine, including reducing the hunt ratio so that it occurs more often, and removing catpower from the trade limiters. I also chose to reduce the triggers for each race to 80% instead of 95% since we already only trigger when gold hits 95%. I think this is far since it helps trade more which also is our best blueprint production method.

Issues Fixed:

#49 , #48 , #46 

Features included in no particular order:

1) fix gameLog sizing issue so that it has more than a fixed width
2) show summary output in green
3) show live activity messages in blue with a checkbox to disable them
4) add ability to continue trading even if capped (set for Leviathans) No current interface to configure

5) add stocks configuration via window.prompt()

Various other code refactors.

### CODE REVIEW

**Comment by cameroncondry** [comment]
I like stocks being in their own area again. I had everything separated like that to begin with, and definitely should have kept it that way.

With the amount of control there is now, the "luxury" category seems safe to remove. There are a few early game tweaks that you have to use in the interface to get the parchments and hunts to play nicely, but overall think the change is good.

I'm currently testing the tweaks to trading, and overall am happy with the update. Main thing I feared, that adding catpower as a limiter would be detrimental, but I think this solution will work decently for the time being. Trades are a new addition in terms of script age, so there are bound to be kinks.

The addition of eludium is nice as well, was planning on adding it in the very near future if nobody else added it.

**Comment by jacob-keller** [comment]
Yea, this ended up removing catpower limiter, but as long as you lower the hunt-ratio it works fine, and controlling the stocks makes the luxury goods distinction worse than it was before.

We still need to figure out the trade issue.I have a suggested fix for this I will push into this series shortly.

**Comment by jacob-keller** [comment]
I added a possible fix for #49

**Comment by jacob-keller** [comment]
This pull request has gotten rather ginormous, hasn't it?

I updated the description above.

It should now fix #48 with ability to configure showing live activity via checkbox, as well as summary (separate messages even!). This way, users can quickly click "show summary" for a way to see activity since last session, and still see live updates.

It should also fix #49 though I haven't been able to tell since I can't trade with Leviathans.

**Comment by cameroncondry** [comment]
Definitely a lot here, but breaking up the commit messages is good enough to keep things separated out. So far I only have issue with the visual representations. I don't care much for the general actions to show as the same color as a game created message. I'd like to keep those colors separated. The color choice on show activity needs to be darkened a bit as well due to it being harder to read on some of the game's color schemes. Lastly, the stock opens are nice with the dialog box, but I'm not loving the toggle button for it since it is in a different location than the other toggle options. I'd like to see it floated right to keep the interface consistent as possible with the crazy amount of options now.

I do like how everything is working as a whole though. I think tweak the colors a bit and I can have this merged in by the end of the day today.

**Comment by jacob-keller** [comment]
Responses inlined for readability.

On May 15, 2015 7:06 AM, "Cameron Condry" <notifications@github.com> wrote:
>
> Definitely a lot here, but breaking up the commit messages is good enough to keep things separated out.

Thanks. I try to keep everything separated cleanly.

>So far I only have issue with the visual representations. I don't care much for the general actions to show as the same color as a game created message.

I don't understand what you mean? All the message() options should be
modified so that they appear in dark purple like they did before.
Nothing about that will have changed. Is it not showing up dark purple
anymore?

(Note, that i use the inverted color scheme so maybe that is why they
show up differently for me? I tried out various color schemes quickly
and saw they were all different though my colors are definitely tuned
to dark mode)

>I'd like to keep those colors separated. The color choice on show activity needs to be darkened a bit as well due to it being harder to read on some of the game's color schemes.

As far as I can tell they *are* separated. Ie: kitten scientists
options messages = purple, summary = green, and activity = blue, while
regular messages are default (black).

I don't really care what color messages are so if you'd like to
propose some better options I am all ears.

>Lastly, the stock opens are nice with the dialog box, but I'm not loving the toggle button for it since it is in a different location than the other toggle options.
> I'd like to see it floated right to keep the interface consistent as possible with the crazy amount of options now.
>

My main concern when I tried this is that it looked really weird. I'm
not sure if where it is now is worse than being on the right side or
not. It felt very awkward to be a lone floated-right at the bottom.
Maybe if I put it next to the crafting section? I have a possible idea
but I won't have time to get to that till later.

What if we did something like:

[] crafting ---------------- <stock> <crafts>

where clicking stocks would show all stocks, and clicking crafts would
show all crafts?

I think that would fit more naturally.

I also have a proposal to only show/store the settings the user wants,
so they can click an "add stock" and insert a stock limit for a
resource, and can click a "delete" button. to remove it.

I think this will make a much more user friendly interface here.

> I do like how everything is working as a whole though. I think tweak the colors a bit and I can have this merged in by the end of the day today

If you're willing to wait on the stock update, and have better color
suggestions, go ahead and merge this with any color changes you wanted
to see. I think it should already be showing actual kittens game
messages in their own color just fine as it is now.

Regards,
Jake

**Comment by cameroncondry** [comment]
Currently, for me as of about 30 minutes ago, the "kittens have crafted" activity is in the same blue that you see when rifts and blueprints event happen in the normal system. That makes it hard to differentiate script events and game events.

My suggestion there is to leave the options purple, shift the summary green to a slightly darker version to show on all color schemes better, and to switch kitten activity to something that doesn't show up currently. Maybe a red/orange similar to the default color for scaffolds and ships. Mainly just a color that isn't generated by the game itself in the game log.

I like the idea of having the stock toggle near the crafting toggle, as I agree it would be a little strange to have stocks floating at the end. Could even try to the right of the engine button, since that one doesn't have any drop downs inherently.

I'm indisposed for the next few hours, but will definitely get any changes you have up, and may tweak the colors slightly before pulling everything in if you haven't already.

Thank you!

**Comment by jacob-keller** [comment]
I won't be able to do anything for at least another 12 hours or so. I am
willing to work on the stock stuff after, but it sounds like you know a lot
better suggestion for colors.

My guess is the blue I picked justhappens to be the same blue as the other
option. It was not intentional.

**Comment by jacob-keller** [comment]
Alright, I finally re-wrote the stuff here.

I added a more advanced method of managing stocks, so that we only show stocks we have defined. This makes it much easier to quickly see at a glance what kind of stocks are in place (vs wading through a sea of zeros)

In addition, I added slight bordering around all items with invisible options, so that it was much more obvious if you click a hidden "stocks" and "items" button it will show stuff. This also makes it much more visually distinctive and easier to see which "items" button you are clicking.

I changed the colors, and I think they look much nicer on all game styles, you were definitely right there.

Hopefully this series is ready for pulling.

I definitely think this should increase version pretty substantially as it is a huge set of changes.

**Comment by jacob-keller** [comment]
I included another commit in a different request, because I thought it was a bit less acceptable change.

If you do not want the options commit, please pull this series, otherwise please pull the other series which should be identical but with the additional commit.

Please don't pull both without letting me rebase, as I'm unsure if that will create double-commit messages in the history log, depending on how you do it.

**Comment by cameroncondry** [comment]
I am going to pull this version instead of the one with labels showing items instead of toggling the checkbox. Main reasons are the options that don't have "items" do nothing unless you click the checkbox itself. The other reason is it goes against how common web forms work, where clicking the label toggling the checkbox is the norm. If the requests are there to change up how it works, then we can definitely talk about it, just would like to keep things consistent for now.

Loving the color changes, they are different enough from the system generated messages and display fine on all color schemes. I would like to see the dividing lines for togglable options be slightly fainter, and the stock add to be a dropdown of available options. Another addition might be adding a boxshadow around "buttons" like the "add stock" to give a bit more visual indication on what is going to happen. However, all of those can be added later.

Everything seems to be working quite well, and I will go ahead and pull this commit in. However, I agree with this being another major version release, but it will be a bit before I can update the changelog and reddit post on the updates.

**Pull request merged**
