### PR TITLE
Refactor tab handling into a TabManager

### PR DESCRIPTION
**Pull request by jacob-keller**
You mentioned this on a different pull request. I believe this works, it has worked so far for Faith, and I am hoping it will find a building shortly to test. I modified both Trading and Building and Festivals and the Religion options to use a new Tab object.

We should be able to extend any Tab object with whatever methods we need. For now I kept them simple. It might be worth actually incorporating more of the functionality in the tab itself, but I figured it was easier to just get the minimum tab portions there.

I tried to use a simple inheritance so that we can just do new BonfireTab() and get a handler for the Bonfire, and so forth. This should be split up evenly for convenient viewing.

It has worked successfully for both festivals, buildings, and praising. I haven't yet had it hit correct resource alignment for trading but the principle is the same.

### CODE REVIEW

**Comment by sjdrodge** [comment]
This looks good to me. The only thing I'm unsure about is whether getBuildingButton and getTradeButton should throw exceptions or just return undefined when they can't find the button they are looking for. I can see arguments for either behavior.

**Comment by cameroncondry** [comment]
I would agree. I think at the very least it should output into the console instead of completely halting the script.

**Comment by cameroncondry** [comment]
@jacob-keller these changes are close to what I was envisioning. I'm going to pull this into the develop branch and work off that for the new interface enhancements. Finally free to sit down and actually implement what I've been toying with.

**Comment by jacob-keller** [comment]
The reason for this is because user never enters building or race names. Same with tabs. We could catch them and write the exception text to the message log though.

The reason for this is to help quickly catch errors due to misnamed items. Essentially, we should *never* throw an exception in practice, so if it happens it should be an error.

**Comment by sjdrodge** [comment]
@cameroncondry is there any way we can get your finalized version of this refactor merged into master? I'm working on getting @jcranmer's deep-building/crafting changes into shape for a merge, and I don't want to step on the changes in your new development branch in the process. I'd also like to add some code to `TabManager` that encapsulates our new approach for only clicking buttons when we actually can/should.

**Comment by cameroncondry** [comment]
@sjdrodge I'm getting close to what can be merged in. I'm combining multiple issues, minus the deep building for now, and will need to set up the changelog before committing to master.

**Comment by sjdrodge** [comment]
@cameroncondry Okay. One thing to keep in mind, though, is that crafting of derivative resources like gears and megaliths should never be done if we also have a capacity for deep building, where the idea is to craft just-in-time, thus making full use of increasing craft ratios. In other words, the two drivers of crafting are: 1) resources approaching their maximum capacity, and 2) construction demand.

I bring this up because a brief look at your development branch suggested to me that you might be putting effort into somewhat more complex crafting rules (though I admit I did not read carefully, so I may be completely wrong).

I suppose it's worth mentioning, for the sake of completeness, that there is also a 3rd driver for crafting, which is "luxury" resource demand, i.e. compendiums, blueprints, and ships (tankers have thus far struck me as being completely undesirable, but maybe I am playing differently than others). The "right" policy for handling these is not yet clear to me, but your current luxury system of constant demand w/ stock limits seems to work well enough so far.

**Comment by cameroncondry** [comment]
@sjdrodge I definitely agree with complex crafting and being weary of when they build. I've set them all to be disabled by default, and when you enable them, it is usually for a short period of time. This does set up nicely for the just in time crafting from the deep build addition. However, I'm going to save deep building for a separated branch/commit, since that will delay me too long.

I tend to agree the current systems work well enough for now, but they aren't ideal. With more and more systems being added though, I do see the triggers improving. I've been seeing this script as a simple helper that just does the more mundane tasks, meaning a user should always be at the helm to make the harder decisions. As more effort is put into it though, I see the potential for it to run the game completely autonomously. One big aspect would be to get kitten jobs and science/upgrades in place before it will be 100% auto pilot, but I can dream... right?

On a more serious note, I should have the last portion of the update complete within the next day. I am down to buildings and some cleanup. The ability to control what buildings/crafts get built is in place, and the system tests I've been running are going quite nice with the updates. I will ask if I can get at least one or two people testing on the development branch before I pull it into master though. In lieu of automated testing, fresh eyes are the best source for testing.

**Comment by sjdrodge** [comment]
Sounds great. I'll go ahead and take care of merging deep building once these new changes stabilize, as I have a few clean-ups and bugfixes for it sitting in my local branch.

**Pull request merged**
