### PR TITLE
Improve overall performance

### PR DESCRIPTION
**Pull request by oliversalzburg**
I noticed that Kittens Game would be very slow to respond and consume a lot of CPU time. I analyzed which calls take up a lot of resources and optimized several paths.

### CODE REVIEW

**Comment by oliversalzburg** [comment]
Okay, this doesn't really work and I understand the `.render()` calls better now. If the buttons aren't rendered, then they don't even exist. I guess, this wasn't even really a problem until 45a87d309abf83125a59a35c4f0c1e625a783c98

I'll see what I can do.

**Comment by oliversalzburg** [comment]
Alright, the last commit fixes not being able to build if not on the build page. I'll continue testing to see if the other tabs are working fine.

**Comment by cameroncondry** [comment]
That reminds me of the reason I stayed away from using the buttons for interaction, in favor of searching the codebase for the raw methods that fire off events. Ultimately was aiming to not need the interface to run the script as a supporting role to the game.

**Comment by oliversalzburg** [comment]
@cameroncondry Yeah, I can totally see this being an issue :) But I'm constantly testing and trying to reduce the `.render()` calls while maintaining functionality. It's getting pretty good with the latest commit. I'll let you know when I'm confident in this PR. I'll squash the commits once it's stable.

**Comment by oliversalzburg** [comment]
@cameroncondry I've been using this change since I proposed it and I can't report any issues. It would be really cool if you could merge it.

**Comment by cameroncondry** [comment]
Perfect, thank you. Was waiting for you to confirm that it was ready, merging.

**Pull request merged**
