### PR TITLE
Local storage - Building, Crafting, Trading

### PR DESCRIPTION
**Pull request by magus424**
Resolves issue #75

### CODE REVIEW

**Comment by jacob-keller** [comment]
Nice. My one suggestion would be to store a version  field in case we need
to change format in the future. Also is there any known way to
automatically reload the script when we refresh the page? At least storing
settings is really great!

**Comment by cameroncondry** [comment]
Reloading the script on refresh would require something like greasemonkey, or some external script manager that says to load up the script.

I agree with adding the version to local storage information, mainly to help with making sure the data is consistent. I have a few other minor tweaks on the code quality, but overall, this is a very good pull request. Thank you for adding this, it has been requested for some time now.

**Comment by magus424** [comment]
What are the code tweaks? I can make them as I add a version # as well :)

**Comment by magus424** [comment]
Re-ran EasyAlign with different settings over those lines, so those should be better now

**Comment by cameroncondry** [comment]
I've been running this today, and it looks very solid. I love the quality in what you've added, very well thought out. You already hit a few of the recommendations I was going to make with removing $.ready, and the rest was minor formatting.

I believe this is ready to be pulled into master. However, I am extremely behind on the changelog, but that shouldn't stop this request. Its a fairly transparent addition that people will love to have.

**Pull request merged**
