### PR TITLE
kitten-scientists: implement a simple activity system

### PR DESCRIPTION
**Pull request by jacob-keller**
This patch modifies the game so that we no longer print messages as we
perform actions. Instead, the user may click "show activity" in the
options list in order to print a display of all actions taken by the
scientists since they last clicked it. It conveniently also shows the
previous date as well.

Possibly this might be more valuable as a listing in a display box but I
couldn't figure out how to do that.

Instead, this just allows us to condense all our output until the user
wants to see it. In this way, after long absense from the game such as
over night or several days, the user can easily see what was acomplished.

Signed-off-by: Jacob Keller <jacob.keller@gmail.com>

### CODE REVIEW

**Comment by cameroncondry** [comment]
This is a fun update, I'm testing it now to see if there are any issues.

**Comment by cameroncondry** [comment]
So far I am loving this update. However, a few issues I have with the system. First is the "show activity" button. I think it should be moved near the "clear log" button and be turned into a link or button to show that it can be interacted with.

I would also like to see it as a toggle, which could come later, since when you're actively playing, it is nice to see things like buildings being built.

Spending some more time with it before pulling it into master. Feel free to keep editing this pull request if you are able to enhance the system.

**Comment by jacob-keller** [comment]
Actually, I've found that clicking it is much nicer since even if you're actively playing you can just click when you need it.

I am thinking a good solution is maybe an automatic display which will show activity every few minutes if you have it enabled? so that you still don't see it always. I also want to modify it so that it shows how many years, rather than previous date.

I'm not sure how to move it to the clear log location though. Any suggestions?

In the long term, I was thinking some sort of dojo dialog would be best, but I am not very familiar with dojo.

**Comment by jacob-keller** [comment]
We can underline the text for the button.

**Comment by cameroncondry** [comment]
I'm becoming fond of clicking the activity button as well. There is a way to get the button next to the clear log button, however, it requires a bit of dom manipulation. I think an easy middle ground would be to display the button after the donation address with some spacing between it and the address.

I don't think an automatic display is needed for now, as long as the activity button is apparent.

**Comment by cameroncondry** [comment]
Simple example of what I mean.

capture

**Comment by jacob-keller** [comment]
Think I prefer sticking it near clear log.

**Comment by cameroncondry** [comment]
Either way honestly. Once the activity button is more apparent, I think this is ready to be merged in. I've not run into any obvious issues.

**Comment by jacob-keller** [comment]
I've updated this now, it includes a couple extra fixes:

First, modify the gameLog so that we hide the scrollbar, since the full panel actually scrolls properly. Also, I put show activity button floating right on the same line as clear log. This looks much nicer.

I also added code to show the number of in game days and years instead of showing the date. This is faster for parsing approximately how long it has been.

I really like this now, and removing the extra scroll bar is something I think makes it look a lot nicer.

**Comment by cameroncondry** [comment]
Loving this, will be pulling it in before turning in for the night.

**Pull request merged**
