### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by oliversalzburg**
Also renamed the main script file for easier installation in userscript managers. The `.user` part in the filename is required for Greasemonkey and Tampermonkey to detect it as a userscript. I symlinked the old filename to the new one to make sure users with the old bookmarklet aren't affected.

Some of the functionality took me quite some time to figure out :D I hope the additional documentation helps other developers to get into the script.

### CODE REVIEW

**Comment by cameroncondry** [comment]
Very nice. Seems there is a conflict here as well, but I do love the updated documentation.

**Comment by oliversalzburg** [comment]
@cameroncondry Should be fine now

**Comment by oliversalzburg** [comment]
Changing a file, renaming it and replacing it with a symlink in one commit is a really bad idea :P I'll never do that again

**Comment by oliversalzburg** [comment]
Actually, I'll split it into several commits. I'll need a moment and update the PR shortly.

**Pull request closed without merging**
