### PR TITLE
Fix build issues with 1.4.0.6

### PR DESCRIPTION
**Pull request by eykanal**
This seems to have been a simple issue with the location of button "name" strings having been moved to a number of child properties, causing the `getBuildButton` function in the `BuildManager` prototype to not be able to find button names. In the final commit, I chose the one that seemed stable and returned the correct string.

For what its worth, being completely unfamiliar with the code prior to this commit, I could not figure out where `this.manager.tab.buttons` was being loaded from; I only assume that it's pulling from a game script that was modified with this latest update. Curious to know whether that's correct.

### CODE REVIEW

**Comment by amateur-professional** [comment]
Can vouch for this pull fixing automatic building. Nice work.

**Comment by eykanal** [comment]
Um, so those latest commits should not be part of this. I didn't realize that future commits get added retroactively to the pull request. FWIW, those are an initial and currently not fully working attempt to fix the logging, but that's not part of this.

Can you just pull the first one (just 810ee4d, actually)?

**Comment by eykanal** [comment]
OK, last comment... you can see the long comment I added in ad50162 which describes the issues with the logging. Those comments are accurate. The fix I have here:

- On the one hand, works, because items added to the log persist
- On the other hand, does not work *properly*, because formatting falls off as soon as something else gets added to the log.

That said, I'm not sure what a better fix would be beyond creating a pull request on the actual game code to have it properly return the DOM element that was just created so we can just modify that. So... this highlights the issue, but doesn't really fix it properly.

Sorry that this all got added to the same pull request, that wasn't my intent.

**Comment by coderpatsy** [comment]
The game code currently creates a message's DOM element once, and stores a reference on the message object on `msg.span`. Both `game.msg()` and `game.console.msg()` return a reference to that message object, so you can do any special DOM modifications easy.

How necessary are your log changes after #196?

**Comment by eykanal** [comment]
That made my changes moot. That's probably a better fix anyways, mine was definitely tacky.

**Comment by cameroncondry** [comment]
I resolved the conflict created when merging the other PRs. However, is this correct still valid and working? If so then let me know and I'll merge in this as well.

**Comment by eykanal** [comment]
GIven that everything else you implemented still seems to work, I'm closing this.

**Pull request closed without merging**
