### PR TITLE
buildManager: use internal buttons instead of loaded page

### PR DESCRIPTION
**Pull request by jacob-keller**
This enables building even when it's not the bonfireTab loaded. Do this by
ensuring we render() the bonfireTab first time we need it. Then, we can
just search the buttons list and locate the item and use the onClick()
function. This is much cleaner than having to be loaded on the bonfire tab
directly. This is similar to how automated trading is implemented.

Signed-off-by: Jacob Keller <jacob.keller@gmail.com>

### CODE REVIEW

**Comment by jacob-keller** [comment]
This should work as it's the same way that trading works. However, I am currently testing this overnight, so I will let you know results in the morning :)

**Comment by cameroncondry** [comment]
Great find with getting the buttons without needing to do jquery selectors. I'm running this version as well (haven't tested trading yet), but it definitely looks like you've done your homework.

**Comment by cameroncondry** [comment]
I was unable to straight pull this request in after further testing. The bonfire tab being pulled is the bonfire (old) tab and it doesn't seem like the new bonfire tab has an easy way to access for implementing. I'm working on a solution, that works with tab switching without getting in the user's way.

**Comment by jacob-keller** [comment]
Based on the issues I've found so far I think it doesn't quite work as expected. I can run render() in the console and that seems to work but calling render in the manager doesn't seem to work long term.

**Pull request merged**
