### PR TITLE
some new functions and some bug fixed

### PR DESCRIPTION
**Pull request by Cirn09**
new functions:

- auto build the best unicorn building
- auto transcend
- auto adore the galaxy (reset faith)
- auto "Tempus Fugit"
- auto Combust time crystal
- auto reset timeline

bug fixed:
- i18n 
- craft price 
- game.console.maxMessages not work on some theme

I am sorry for my ugly code. Those functions has been tested by some Chinese players for a week.

### CODE REVIEW

**Comment by cameroncondry** [comment]
So far I am quite happy with these updates. However, the branch currently has conflicts. When you get a chance, please resolve the conflicts and I'll go ahead and pull it into master. Thank you for the great additions!

**Comment by cameroncondry** [comment]
My apologies, should have looked at the conflicts. I went ahead and resolved the issue and merged in your updates. Thanks again for the great additions!

**Comment by oliversalzburg** [comment]
What is the logic behind this piece of code?
```js
var epiphanyRecommend = (1-k+Math.sqrt(80*(k*k-1)*x+(k-1)*(k-1)))*k/(40*(k+1)*(k+1)*(k-1))+x+x/(k*k-1);
```

**Comment by PeterCheney** [comment]
> 这段代码背后的逻辑是什么？
> 
> ```js
> VAR  epiphanyRecommend  =  （1 - ķ +数学。SQRT （80 * （ķ * ķ - 1 ）* X + （ķ - 1 ）* （ķ - 1 ）））* ķ / （40 * （ķ + 1 ）* （k + 1 ) * ( k - 1) ) + x + x / ( k * k - 1 ) ;
> ```
transcendend = TT
- transcendend next level will lose some of faithRatio, x = needNextLevel =  lose faithRaito's value.
- then transcendend level will improve the adore gain  faithRatio value. (1+ TT)^2 = k   = adoreIncreaceRatio

-  the game has changed the religion tab, but in the previous game, more use  praise the sun 's ratio

- so set up an equation 
 - when don't trascendend you adore gain faithRaito's value (praise the sun  ratio) = after trascendend you adore gain faithRatio(praise the sun 's ratio)
 - then simplify

-

**Pull request merged**
