### PR TITLE
Don't recreate TabManager every frame

### PR DESCRIPTION
**Pull request by oliversalzburg**
I'm not sure if there was a reason to re-create it every frame, but it had a serious impact on my performance, so I adjusted this.

I'm currently testing this change in my own fork. Feedback is welcome.

### CODE REVIEW

**Comment by cameroncondry** [comment]
At this point I am not sure why it is recreated every time either. As long as the system works throughout the tabs, then I'd be willing to pull in the update.

**Comment by oliversalzburg** [comment]
@cameroncondry I've also looked into other performance bottlenecks. Do you know why `getTradeButton` needs to call `this.manager.render`? It's quite costly.

**Comment by cameroncondry** [comment]
I believe the original reason was the view had to be rendered before the trade options could be initialized.

**Comment by oliversalzburg** [comment]
Alright, I'll see if I can reduce that to a single initialization call somehow. The festival change seems to be fine BTW. The scientists are still holding festivals in my game.

**Comment by oliversalzburg** [comment]
I will close this PR in favor of a more generic "performance improvement" PR. Which was the goal in the first place :)

**Pull request closed without merging**
