### PR TITLE
kitten-scientists: add trading support

### PR DESCRIPTION
**Pull request by jacob-keller**
This patch updates the kitten scientists to include support for automatic trading. Since I was able to locate trade buttons in the game API, it does not require switching to the trade tab to run. I also fixed up hunting so that parchment is a luxury good and honors a limit for furs.

### CODE REVIEW

**Comment by jacob-keller** [comment]
Please don't pull this directly. I am going to do a manual rebase and clean up all of the bug fixes I've found since running. The original code was written straight into github edit, so it wasn't functional.

I've found a few other issues I am working on resolving right now.

This does lead to some interesting questions about how to handle resource requirements and limits.

I think generally this appears to work, however there is some issue with the trade tab thing not picking up the buttons. I think it's a similar problem with how the bonfire buttons don't get populated (thus forcing you to have to switch tabs to bonfire for building stuff to work!)

The "quick" fix seems to be to load the trade tab once and it seems to keep working going forward.

The other issue I've fixed in my testing involves the trade not checking against gold/manpower bits so it just launches trade constantly draining the gold/manpower reserves.

**Comment by cameroncondry** [comment]
Amazing addition, I will look to pull this in when you feel its complete. I've beena  bit behind on pulling in changes and have a few other PRs that I need to merge together too. 

It looks like you are using the physical buttons on the page to trade, which definitely has downsides. I tried tab switching before, but you have to account for the processing time in order to "check" the buttons. I'm sure there is a way to use the API to simply purchase buildings or trade straight out, however, I haven't sifted through the entire codebase yet.

**Comment by jacob-keller** [comment]
There doesn't seem to be a way to actually do it directly. For trading, it works fine to use this method as long as you load the tab once. You don't actually need to be located on the trade tab (I've tried with the console and it works fine). It doesn't work for buildings because the buttons aren't stored for some reason.

I'm still trying to sort out exactly the best way to do the trade, because right now it's too greedy,and starves both hunting and only the first race is run, because they all rely on gold and catpower. I might shorten it so that only only trades a few times for each race thus allowing hunting to continue.

**Comment by trini** [comment]
IMHO leave the limits and the code well documented.  The main way I use the script today is fork it and modify locally to suit where I am in progress.  For me for example, I could totally ignore hunting right now and just trade up a storm (and rely on Mints for fur).

**Comment by jacob-keller** [comment]
Yea I think that is probably how most people modify it. I don't know how easy setting up CSS/javascript to create a settings panel would be.

I still need to resolve the issue where it will greedily trade with only the first partner. I think I can find a way to get it so that multiple trade races can each get a portion of the gold/manpower.

**Comment by jacob-keller** [comment]
I've proposed a new merge.

**Pull request closed without merging**
