### PR TITLE
Make plugin load after gamePage is available

### LINKED ISSUE #171: Broken in 1.2.0.0
The game is now loaded asynchronously, which causes `gamePage` to not be available when the script is started.

### PR DESCRIPTION
**Pull request by zelenay**
Fixes #171 - The game is now loaded asynchronously, which causes gamePage to not be available when the script is started.

Whole script is wrapped into run() function that is called after gamePage is available. Function loadTest does the check every 2s.

### CODE REVIEW

**Comment by oliversalzburg** [comment]
Did you change the line endings in the second commit? It looks like every single line was changed.

**Comment by zelenay** [comment]
For better reading I intended the whole script because it is wrapped in the function.

**Comment by zelenay** [comment]
Maybe I have to wrap only few last lines - from 

`// add the options above the game log right.prepend(optionsElement.append(optionsListElement));`

I will test it and let you know.

**Comment by zelenay** [comment]
Well, 

I would have to wrap it from line 910:

`if (game.colorScheme !== 'sleek') {`

or modify logic of preparing color scheme in Engine initialization - maybe new Manager first and then wrap only last few lines in run() function.

**Comment by cameroncondry** [comment]
Thank you for the update, I will go ahead and merge.

**Pull request merged**
